# Basic info
replicaCount: "__REQUIRED__"
secretsRef: "__REQUIRED__"
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-ftp-source
  tag: 0.3.0.1
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"

# SSL/TLS options can be enabled, some connectors provide SSL support, others the newer TLS
# Set the corresponding value type to true. For SSL persistent volumes or hostPaths will be
# mounted under /connector-extra-config. Set the connectors ssl/tls option paths to be use this
# TLS is done via Secrets, create a secret for containing the certificates (base64 encoded) and
# create a secret for them, adding the name of the secret to the `secretsRef` other wise if using
# Eneco's Landscaper it will do this for you.

# SSL mount path on hosts, should be the base path of any ssl keystore/truststore paths
ssl:
  enabled: false
  # Path to the directory on the hosts
  path: /ssl

  # If persistent volumes should be used for ssl keystore/truststore paths
  persistentVolumes:
    enable: false
    existingClaim:

# TLS, for those connectors supporting TLS certificates rather than ssl key/truststores
# contents for mount take from config map
tls:
  enabled: false

## Avro schemas, for those connectors, MQTT and JMS source that support Avro converters we
## need the schemas, so we'll mount as a ConfigMap. Set the key value pairs, filename and data
## matching the value option avroSchema. Key is the file name, value is the avro schema contents
#avroSchemaFiles:
#  schema_file_name:  ""






# address ftp address[:port] type: STRING importance: HIGH
address: "__REQUIRED__"

# fileMaxage ignore files older than this; ISO8601 duration type: STRING importance: HIGH
fileMaxage: "__REQUIRED__"

# keystyle what the output key is set to: `string` => filename; `struct` => structure with filename and offset type: STRING importance: HIGH
keystyle: "__REQUIRED__"

# maxPollRecords Max number of records returned per poll type: INT importance: LOW
maxPollRecords: 10000

# monitorTail comma separated lists of path:destinationtopic; tail of file is tracked type: LIST importance: HIGH
monitorTail: 

# user ftp user name to login type: STRING importance: HIGH
user: "__REQUIRED__"

# sourcerecordconverter TODO type: CLASS importance: HIGH
sourcerecordconverter: com.datamountaineer.streamreactor.connect.ftp.source.NopSourceRecordConverter

# maxBackoff on failure, exponentially backoff to at most this ISO8601 duration type: STRING importance: HIGH
maxBackoff: PT30M

# monitorUpdate comma separated lists of path:destinationtopic; whole file is tracked type: LIST importance: HIGH
monitorUpdate: 

# password ftp password to login type: PASSWORD importance: HIGH
password: "__REQUIRED__"

# fileconverter TODO type: CLASS importance: HIGH
fileconverter: com.datamountaineer.streamreactor.connect.ftp.source.SimpleFileConverter

# refresh how often the ftp server is polled; ISO8601 duration type: STRING importance: HIGH
refresh: "__REQUIRED__"

